# 메트릭 서버(파드의 자원상황 모니터링 툴) 설치
# kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

# Horizontal Pod Autoscaler(=스케일 아웃)
# 컨테이너 자동 확장
# 10분 지나고 나서 부하가 없을 시에 자동으로 기본 pod 대수로 돌아옴
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ordersystem-hpa
  namespace: jin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ordersystem-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

  # 부하 테스트 linux 스크립트 (pod안에 들어가서 돌릴 것)
    # kubectl exec -it 파드명 -n 네임스페이스 -- bash
    # while true; do curl -s http://ordersystem-service/product/list; done

  # 부하 모니터링
    # -w : watch 옵셥
    # kubectl get hpa ordersystem-hpa -n jin -w