server:
  port: 8080
spring:
#  config:
#    activate:
#      on-profile: local
#      on-cloud-platform:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/ordersystem
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    # spring에서 db로의 커넥션 개수 제한
    # 기본적으로 대략 10개 가량의 커넥션이 1개의 서버에서 발생
    tomcat: 5

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  redis:
    host: ${REDIS_HOST}
    port: 6379

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    root: info
jwt:
  expiration: 30
  secretKey: ${JWT_SECRET}
  expirationRt: 14400
  secretKeyRt: ${JWT_SECRET_RT}

# aws s3 설정
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: us-east-1
      auto: false
    s3:
      bucket: my-fav-book

